name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 #

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Specify the Node.js version you use
        cache: 'npm' # Enable caching for faster dependency installation

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build
